#pragma once

DWORD WINAPI IPFGetVersion(VOID);
BOOL  WINAPI IPFSetFilter(PFILTER, UINT);
BOOL  WINAPI IPFDelFilter(PFILTER, UINT);
DWORD WINAPI IPFEnumFilter(LPVOID, UINT);
BOOL  WINAPI IPFStartFilter(VOID);
BOOL  WINAPI IPFStopFilter(VOID);
BOOL  WINAPI IPFStartLog(VOID);
BOOL  WINAPI IPFStopLog(VOID);
BOOL  WINAPI IPFSetLog(PLOGBUF, UINT);
DWORD WINAPI IPFGetLogBuffer(PLOGBUF, UINT);
DWORD WINAPI IsServiceInstalled(VOID);
